#!/bin/bash
# basic script
# autor: Carlos Nascimento, 28.08.16
# What do:
# get user response and show system info

echo "Show system info [s/n]"
read RESPONSE
test "$RESPONSE" = "n" && exit

# show data system
echo "Date"
date

# show disck info
echo "Disck info"
df

# show users
echo "Users"
w

